### ISSUE TITLE
Would like to get ScriptID as well

### ISSUE THREAD

**Issue by thlorenz** [vkurchatkin/function-origin#1]
Was wondering if you're open to adding [scriptID](https://code.google.com/p/v8/source/browse/trunk/include/v8.h#2815) to properties we pull out of a function.

I realize it goes against the original intent of this module, but script id can be highly useful when comparing this data to a heapdump.

So checking what you think and will submit a PR if all is ok.

**Comment by vkurchatkin** [comment]
Go ahead, seems useful
