### ISSUE TITLE
compare/contrast with callsite

### ISSUE THREAD

**Issue by ORESoftware** [vkurchatkin/function-origin#7]
Perhaps in the readme, do you think you could compare and contrast this lib with "callsite"?

https://github.com/tj/callsite

It would help me make a determination about which to use, thanks

**Comment by vkurchatkin** [comment]
@ORESoftware they don't really have much in common. `callsite` gives you access to frames of current stack, so you can access information about a specific function only if it is currently on the stack. 

For example:

``` js
var callsite = require('callsite');

function baz() {
  const stack = callsite();
  const frame = stack[0];
  console.log(frame.getFunctionName());
  console.log(frame.getFileName());
  console.log(frame.getLineNumber());
}

baz();
```

Will print:

```
baz
.../file.js
4
```

Where 4 would a line where you call `callsite`, which is not very useful.

`function-origin` allows you to get function info just by passing a reference:

``` js
var fo = require('function-origin');

function baz() {
}

console.log(fo(baz))
```

Hope this helps

**Comment by ORESoftware** [comment]
thanks for this info, it may prove useful for me!
